name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
         
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: false

      - name: Build Site
        run: |
          cp -R exampleSite/* .
          hugo --minify --themesDir ../ --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/"
          
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
